config/routes.rb
Rails.application.routes.draw do

  resources :abouts


  root to: 'home#index'

  resources :markers
  get '/markers/create'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marker.rb
class Marker < ApplicationRecord
  has_attached_file :icon, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/missing.png"
  validates_attachment_content_type :icon, content_type: /\Aimage\/.*\z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
      render :layout => false
  end
end

app/controllers/markers_controller.rb
class MarkersController < ApplicationController
  before_action :set_marker, only: [:show, :edit, :update, :destroy]

  # GET /markers
  # GET /markers.json
  def index
    @markers = Marker.all
  end

  # GET /markers/1
  # GET /markers/1.json
  def show
  end

  # GET /markers/new
  def new
    @marker = Marker.new
  end

  # GET /markers/1/edit
  def edit
  end

  # POST /markers
  # POST /markers.json

      skip_before_action :verify_authenticity_token

  def create
    @marker = Marker.new(marker_params)

    respond_to do |format|
      if @marker.save
        format.html { redirect_to @marker, notice: 'Marker was successfully created.' }
        format.json { render :show, status: :created, location: @marker }
      else
        format.html { render :new }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /markers/1
  # PATCH/PUT /markers/1.json
  def update
    respond_to do |format|
      if @marker.update(marker_params)
        format.html { redirect_to @marker, notice: 'Marker was successfully updated.' }
        format.json { render :show, status: :ok, location: @marker }
      else
        format.html { render :edit }
        format.json { render json: @marker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /markers/1
  # DELETE /markers/1.json
  def destroy
    @marker.icon = nil
    @marker.save
    @marker.destroy
    respond_to do |format|
      format.html { redirect_to markers_url, notice: 'Marker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marker
      @marker = Marker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marker_params
      params.require(:marker).permit(:title, :lat, :lon, :kind, :description, :link, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/markers_helper.rb
module MarkersHelper
end

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag('/js/daystyle.js') %>
    <%= javascript_include_tag('/js/nightstyle.js') %>
    <%= javascript_include_tag('/js/maploader.js') %>


    <title>Wander</title>

    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">

    <style>
      #map {
        height: 100%;
      }
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top opaque-navbar" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
                    <span class="glyphicon glyphicon-chevron-right" style="color:white;"></span>
                </button>
                <a class="navbar-brand" href="/">WanderShot</a>
            </div>

            <div class="collapse navbar-collapse" id="navMain" role="navigation">
                <ul class="nav navbar-nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nature</a>
                        <ul class="dropdown-menu">
                            <li><a href="/markers">Discover</a></li>
                            <li><a href="/markers/new">Record</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Urban</a>
                        <ul class="dropdown-menu">
                            <li><a href="/markers">Discover</a></li>
                            <li><a href="/markers/new">Record</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Indoor</a>
                        <ul class="dropdown-menu">
                            <li><a href="/markers">Discover</a></li>
                            <li><a href="/markers/new">Record</a></li>
                        </ul>
                    </li>
                    <li class="aboutbutton"><%= link_to "About", "/abouts"  %></li>
                </ul>
            </div>
      </div>
    </div>

    <div id="map"></div>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAZ781P8-RMwzrbJOSnkidmFaXbNGn_aoA&callback=initMap"
    async defer></script>

    <div id="form" style="display: none;">
          <table>
          <tr><td>Title:</td> <td><input type='text' id='title'/> </td> </tr>
          <tr><td>Description:</td> <td><input type='text' id='description'/> </td> </tr>
          <tr><td>Link:</td> <td><input type='text' id='link'/> </td> </tr>
          <tr><td>Kind:</td> <td><select id='kind'> +
                     <option value='nature' SELECTED>Nature</option>
                     <option value='history'>Urban</option>
                     <option value='shops'>Indoor</option>
                     </select> </td></tr>
                     <tr><td></td><td><button type="button" onclick="saveData()">Save</button></td></tr>
          </table>
        </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Wander" %></title>

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag('/js/test.js') %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->


    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag '/images/favicon.ico', :rel => 'shortcut icon' %>


  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top opaque-navbar">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navMain">
                    <span class="glyphicon glyphicon-chevron-right" style="color:white;"></span>
                </button>
                <a class="navbar-brand" href="/">WanderShot</a>
            </div>

        <div class="collapse navbar-collapse" id="navMain">
            <ul class="nav navbar-nav pull-right">
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Nature</a>
                    <ul class="dropdown-menu">
                        <li><a href="/markers">Discover</a></li>
                        <li><a href="/markers/new">Record</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Urban</a>
                    <ul class="dropdown-menu">
                        <li><a href="/markers">Discover</a></li>
                        <li><a href="/markers/new">Record</a></li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">Indoor</a>
                    <ul class="dropdown-menu">
                        <li><a href="/markers">Discover</a></li>
                        <li><a href="/markers/new">Record</a></li>
                    </ul>
                </li>
              <li class="aboutbutton"><%= link_to "About", "/abouts"  %></li>
            </ul>
        </div>
      </div>
    </div>

<!--
<nav class="navbar navbar-inverse navbar-fixed-top" id="sidebar-wrapper" role="navigation">
  <ul class="nav sidebar-nav">
    <li class="sidebar-brand">
      <a href="#">
        Brand
      </a>
    </li>
    <li>
      <a href="#">Home</a>
    </li>
    <li>
      <a href="#">About</a>
    </li>
    <li>
      <a href="#">Events</a>
    </li>
    <li>
      <a href="#">Team</a>
    </li>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Works <span class="caret"></span></a>
      <ul class="dropdown-menu" role="menu">
        <li class="dropdown-header">Dropdown heading</li>
        <li><a href="#">Action</a></li>
        <li><a href="#">Another action</a></li>
        <li><a href="#">Something else here</a></li>
        <li><a href="#">Separated link</a></li>
        <li><a href="#">One more separated link</a></li>
      </ul>
    </li>
    <li>
      <a href="#">Services</a>
    </li>
    <li>
      <a href="#">Contact</a>
    </li>
    <li>
      <a href="https://twitter.com/maridlcrmn">Follow me</a>
    </li>
  </ul>
</nav>-->


    <div class="container mycontainer">
      <div class="row">
        <div class="col-lg-12">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>
        <p>&copy; Adit Parikh 2017</p>
      </footer>
    </div> <!-- /container -->


  </body>
</html>

app/views/markers/_form.html.erb
<%= form_for @marker, :html => { :class => "form-horizontal marker", :multipart => true } do |f| %>
  <% if @marker.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@marker.errors.count, "error") %> prohibited this marker from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @marker.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>

  <div class="form-group">
    <%= f.label :lat, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lat, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lat) %>
  </div>

  <div class="form-group">
    <%= f.label :lon, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :lon, :class => 'form-control' %>
    </div>
    <%=f.error_span(:lon) %>
  </div>

  <div class="form-group">
    <%= f.label :kind, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :kind, [ 'nature','history','shops' ]%>
    </div>

    <%=f.error_span(:kind) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>

    <%=f.error_span(:description) %>
  </div>

  <div class="form-group">
    <%= f.label :link, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :link, :class => 'form-control' %>
    </div>
    <%=f.error_span(:link) %>
  </div>

    <div class="form-group">
      <%= f.label :Image, :class => 'control-label col-lg-2' %>
        <%= f.file_field :icon %>
    </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                markers_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/markers/edit.html.erb
<%- model_class = Marker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/markers/index.html.erb
<%- model_class = Marker -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div class="table-responsive">
<table class="table">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:kind) %></th>
      <th><%= model_class.human_attribute_name(:icon) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @markers.each do |marker| %>
      <tr>
        <td><%= link_to marker.title, marker_path(marker)  %></td>
        <td><%= marker.kind %></td>
        <td><%= image_tag marker.icon.url(:thumb) %></td>
        <td>
          <%= link_to t('.show', :default => t("helpers.links.show")),
                      marker_path(marker), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_marker_path(marker), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      marker_path(marker),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_marker_path,
            :class => 'btn btn-primary' %>

app/views/markers/new.html.erb
<%- model_class = Marker -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/markers/show.html.erb
<%- model_class = Marker -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @marker.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lat) %>:</strong></dt>
  <dd><%= @marker.lat %></dd>
  <dt><strong><%= model_class.human_attribute_name(:lon) %>:</strong></dt>
  <dd><%= @marker.lon %></dd>
  <dt><strong><%= model_class.human_attribute_name(:kind) %>:</strong></dt>
  <dd><%= @marker.kind %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @marker.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:link) %>:</strong></dt>
  <dd><%= @marker.link %></dd>
  <dt><strong><%= model_class.human_attribute_name(:icon) %>:</strong></dt>
  <dd><%= image_tag @marker.icon.url(:thumb) %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              markers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_marker_path(@marker), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              marker_path(@marker),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>